services:
  - type: web
    name: tahanan
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: CI_ENVIRONMENT
        value: production
      - key: MYSQL_PUBLIC_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
