<?= $this->extend('layouts/coffeehouse') ?>

<?= $this->section('content') ?>
<section class="form-page"><div class="shell form-layout"><div class="form-intro"><p class="context-line"><?= esc($eyebrow) ?></p><h1><?= esc($heading) ?></h1><p>Give each team member the details they need to begin a shift at Tahanan.</p><a class="back-link" href="<?= site_url('users') ?>">Back to the house team</a></div><div class="form-card">
<?php if ($success): ?><div class="notice notice--success" role="status"><?= esc($success) ?></div><?php endif ?>
<?php if ($errors): ?><div class="validation-summary" role="alert"><strong>Please correct the highlighted fields.</strong><ul><?php foreach ($errors as $error): ?><li><?= esc($error) ?></li><?php endforeach ?></ul></div><?php endif ?>
<form action="<?= esc($action) ?>" method="post" enctype="multipart/form-data" novalidate><?= csrf_field() ?>
<?php if ($user !== null): ?><?php $avatar = empty($user['avatar']) ? base_url('assets/images/avatar-placeholder.svg') : (preg_match('#^https?://#', (string) $user['avatar']) ? $user['avatar'] : base_url('uploads/avatars/' . rawurlencode($user['avatar']))); ?><div class="avatar-editor"><img data-avatar-preview src="<?= esc($avatar) ?>" alt="Current profile picture for <?= esc($user['full_name']) ?>"><div><strong>Current profile picture</strong><span>New images are cropped to a 320 × 320 pixel square.</span></div></div><?php endif ?>
<div class="field <?= isset($errors['username']) ? 'field--error' : '' ?>"><label for="username">Username <span>Required and unique</span></label><input id="username" name="username" type="text" maxlength="50" value="<?= esc(old('username', $user['username'] ?? '')) ?>" aria-describedby="username_help" <?= isset($errors['username']) ? 'aria-invalid="true"' : '' ?>><small id="username_help"><?= isset($errors['username']) ? esc($errors['username']) : 'Letters, numbers, periods, underscores, and hyphens only.' ?></small></div>
<div class="field <?= isset($errors['full_name']) ? 'field--error' : '' ?>"><label for="full_name">Full name <span>Required</span></label><input id="full_name" name="full_name" type="text" maxlength="100" value="<?= esc(old('full_name', $user['full_name'] ?? '')) ?>" aria-describedby="full_name_help" <?= isset($errors['full_name']) ? 'aria-invalid="true"' : '' ?>><small id="full_name_help"><?= isset($errors['full_name']) ? esc($errors['full_name']) : 'Enter the team member’s complete name.' ?></small></div>
<div class="field <?= isset($errors['email']) ? 'field--error' : '' ?>"><label for="email">Email address <span>Required</span></label><input id="email" name="email" type="email" maxlength="100" value="<?= esc(old('email', $user['email'] ?? '')) ?>" aria-describedby="email_help" <?= isset($errors['email']) ? 'aria-invalid="true"' : '' ?>><small id="email_help"><?= isset($errors['email']) ? esc($errors['email']) : 'Use a valid email address such as name@example.com.' ?></small></div>
<div class="field <?= isset($errors['password']) ? 'field--error' : '' ?>"><label for="password">Password <span><?= $user === null ? 'Required' : 'Optional change' ?></span></label><input id="password" name="password" type="password" maxlength="72" autocomplete="new-password" aria-describedby="password_help" <?= isset($errors['password']) ? 'aria-invalid="true"' : '' ?>><small id="password_help"><?= isset($errors['password']) ? esc($errors['password']) : ($user === null ? 'Use at least 8 characters.' : 'Leave blank to keep the current password; enter 8 or more characters to replace it.') ?></small></div>
<?php if ($user !== null): ?><div class="field field--file <?= isset($errors['avatar']) ? 'field--error' : '' ?>"><label for="avatar">Profile picture <span>Optional</span></label><input id="avatar" name="avatar" type="file" accept="image/jpeg,image/png" aria-describedby="avatar_help" data-avatar-input <?= isset($errors['avatar']) ? 'aria-invalid="true"' : '' ?>><small id="avatar_help"><?= isset($errors['avatar']) ? esc($errors['avatar']) : 'JPG or PNG only, maximum 2 MB. The image will be cropped to a square thumbnail.' ?></small></div><?php endif ?>
<div class="form-actions"><button class="button button--primary" type="submit"><?= esc($submitLabel) ?></button><a class="text-link" href="<?= site_url('users') ?>">Cancel</a></div></form></div></div></section>
<?= $this->endSection() ?>
