<?= $this->extend('layouts/coffeehouse') ?>

<?= $this->section('content') ?>
<section class="directory-header directory-header--espresso"><div class="shell directory-header__grid"><div><p class="context-line">Staff access</p><h1>User accounts</h1><p>Create accounts, maintain contact details, and prepare profile pictures for display.</p></div><div class="directory-total"><strong><?= count($users) ?></strong><span>managed <?= count($users) === 1 ? 'account' : 'accounts' ?></span></div></div></section>
<section class="directory-section"><div class="shell">
    <?php if (session('success')): ?><div class="notice notice--success" role="status"><?= esc(session('success')) ?></div><?php endif ?>
    <div class="directory-tools"><label class="search-box" for="user-search"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7"></circle><path d="m16 16 5 5"></path></svg><span class="sr-only">Search user accounts</span><input id="user-search" type="search" data-table-search="user-table" aria-controls="user-table" placeholder="Search user accounts"></label><a class="button button--primary button--compact" href="<?= site_url('users/new') ?>">New user</a></div>
    <div class="table-wrap"><table id="user-table"><thead><tr><th>User</th><th>Username</th><th>Email address</th><th>Action</th></tr></thead><tbody>
    <?php foreach ($users as $user): ?><?php $avatar = empty($user['avatar']) ? base_url('assets/images/avatar-placeholder.svg') : (preg_match('#^https?://#', (string) $user['avatar']) ? $user['avatar'] : base_url('uploads/avatars/' . rawurlencode($user['avatar']))); ?><tr><td data-label="User"><div class="identity"><img class="avatar-image" src="<?= esc($avatar) ?>" alt="<?= esc($user['full_name']) ?> profile picture"><strong><?= esc($user['full_name']) ?></strong></div></td><td data-label="Username"><span class="username">@<?= esc($user['username']) ?></span></td><td data-label="Email"><a href="mailto:<?= esc($user['email']) ?>"><?= esc($user['email']) ?></a></td><td data-label="Action"><a class="table-action" href="<?= site_url('users/' . $user['id'] . '/edit') ?>">Edit</a></td></tr><?php endforeach ?>
    </tbody></table><div class="empty-state" role="status" hidden>No user accounts match your search. Try a name, username, or email address.</div></div>
    <aside class="legacy-panel"><div><p class="context-line">Preserved directory</p><h2>The original Tahanan team</h2><p>These six staff records remain separate from authenticated user accounts.</p></div><div class="legacy-names" aria-label="Legacy staff members"><?php foreach ($legacyUsers as $legacyUser): ?><span><?= esc($legacyUser['full_name']) ?></span><?php endforeach ?></div><a class="text-link" href="<?= site_url('coffeehouse/team') ?>">Open legacy team</a></aside>
</div></section>
<?= $this->endSection() ?>
