<?= $this->extend('layouts/coffeehouse') ?>

<?= $this->section('content') ?>
<section class="directory-header directory-header--espresso"><div class="shell directory-header__grid"><div><p class="context-line">Behind the counter</p><h1>House team</h1><p>Keep each team member’s contact details and staff sign-in ready for the next shift.</p></div><div class="directory-total"><strong><?= count($users) ?></strong><span><?= count($users) === 1 ? 'team member' : 'team members' ?></span></div></div></section>
<section class="directory-section"><div class="shell">
    <?php if (session('success')): ?><div class="notice notice--success" role="status"><?= esc(session('success')) ?></div><?php endif ?>
    <div class="directory-tools"><label class="search-box" for="user-search"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7"></circle><path d="m16 16 5 5"></path></svg><span class="sr-only">Search the house team</span><input id="user-search" type="search" data-table-search="user-table" aria-controls="user-table" placeholder="Search the house team"></label><a class="button button--primary button--compact" href="<?= site_url('users/new') ?>">Add team member</a></div>
    <div class="table-wrap"><table id="user-table"><thead><tr><th>User</th><th>Username</th><th>Email address</th><th>Action</th></tr></thead><tbody>
    <?php foreach ($users as $user): ?><?php $avatar = empty($user['avatar']) ? base_url('assets/images/avatar-placeholder.svg') : (preg_match('#^https?://#', (string) $user['avatar']) ? $user['avatar'] : base_url('uploads/avatars/' . rawurlencode($user['avatar']))); ?><tr><td data-label="User"><div class="identity"><img class="avatar-image" src="<?= esc($avatar) ?>" alt="<?= esc($user['full_name']) ?> profile picture"><strong><?= esc($user['full_name']) ?></strong></div></td><td data-label="Username"><span class="username">@<?= esc($user['username']) ?></span></td><td data-label="Email"><a href="mailto:<?= esc($user['email']) ?>"><?= esc($user['email']) ?></a></td><td data-label="Action"><a class="table-action" href="<?= site_url('users/' . $user['id'] . '/edit') ?>">Edit</a></td></tr><?php endforeach ?>
    </tbody></table><div class="empty-state" role="status" hidden>No team members match your search. Try a name, username, or email address.</div></div>
    <aside class="legacy-panel"><div><p class="context-line">Where we began</p><h2>The original Tahanan team</h2><p>Meet the six people who shaped the house’s first welcome.</p></div><div class="legacy-names" aria-label="Original staff members"><?php foreach ($legacyUsers as $legacyUser): ?><span><?= esc($legacyUser['full_name']) ?></span><?php endforeach ?></div><a class="text-link" href="<?= site_url('coffeehouse/team') ?>">Meet the original team</a></aside>
</div></section>
<?= $this->endSection() ?>
